apiVersion: batch/v1
kind: Job
metadata:
  labels:
  name: oes-config
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: oes-config
    spec:
      containers:
      - command:
        - bash
        - /tmp/config/datasource-api.sh
        image: quay.io/opsmxpublic/oes-pre-configure:v2
        imagePullPolicy: IfNotPresent
        name: datasource-creation-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/config
          name: datasource-creation
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: isd-oes-datasource-creation
        name: datasource-creation
