# This file can be used for very simple installation that uses
# secure urls (i.e. httpS).  This requires that cert-manager be present, the cluster be accessible from internet
# OR you many need to manually create the TLS certificates
# and/or your browser may give a security warning
# Good choice for 1st time ISD Trial with Role Based Access Control using your own ingress and TLS certs
#
# Instructions:
# a) Update the 3 URLs below
# b) Update the git repo details
# c) Route traffic to the three urls mentioned below using your infrastructure
#
global:
  createIngress: false
  certManager:
    installed: false
  commonGate:
    spinnakerRBAC: true 
  oesUI:
    host: oes.isd-pov.example.com
  oesGate:
    host: oes-gate.isd-pov.example.com
  spinDeck:
    host: spin.isd-pov.example.com

spinnaker:
  gitopsHalyard:
    repo:
      baseUrlHostName: github.com # REPLACE for is using enterprise github
      organization: ksrinimba # REPLACE
      username: ksrinimba     # REPLACE
      token: <YOUR TOKEN>    # REPLACE
      repository: YOUR-REPO   # REPLACE repo name for GitOps Halyard (Sample Reference: https://github.com/OpsMx/sample-gitops-repo.git).
      dynamicAccRepository: YOUR-REPO # REPLACE Please provide the repo name of the GitOps Dynamic Accounts Directory


